<?php
function ElsoKerdesek() {
    $output = '';
    $output .= '<label>1.1 Melyik nem SQL utasitas a felsoroltak kozul?</label><br>';
    $output .= '<input type="radio" name="1.1" value="1" >SELECT<br>';
    $output .= '<input type="radio" name="1.1" value="2" >UPDATE<br>';
    $output .= '<input type="radio" name="1.1" value="3" >CREATE QUERY<br>';
    $output .= '<input type="radio" name="1.1" value="4" >DELETE<br>';
    $output .= '<br><br>';
    $output .= '<label>1.2 Melyik utasitassal tudunk lekerdezni adatokat egy SQL szerverrol?</label><br>';
    $output .= '<input type="radio" name="1.2" value="1">GET<br>';
    $output .= '<input type="radio" name="1.2" value="2">SELECT<br>';
    $output .= '<input type="radio" name="1.2" value="3">EXTRACT<br>';
    $output .= '<input type="radio" name="1.2" value="4">PUT<br>';
    $output .= '<br><br>';
    $output .= '<label>1.3 A WHERE belepes BETWEEN 1958 AND 2013 zaradekkal melyik zaradek egyenerteku?</label><br>';
    $output .= '<input type="radio" name="1.3" value="1">WHERE belepes > 1958 AND belepes < 2013<br>';
    $output .= '<input type="radio" name="1.3" value="2">WHERE (belepes > 1958) AND (belepes < 2013)<br>';
    $output .= '<input type="radio" name="1.3" value="3">WHERE belepes > 1958 OR belepes < 2013<br>';
    $output .= '<input type="radio" name="1.3" value="4">WHERE belepes >= 1958 AND belepes <= 2013<br>';
    $output .= '<br><br>';
    $output .= '<label>1.4 A WHERE zaradekban melyik operatort hasznalhatjuk a kisebb/egyenlo kifejezesere?</label><br>';
    $output .= '<input type="radio" name="1.4" value="1">>=<br>';
    $output .= '<input type="radio" name="1.4" value="2"><=<br>';
    $output .= '<input type="radio" name="1.4" value="3">=><br>';
    $output .= '<input type="radio" name="1.4" value="4">=<<br>';
    $output .= '<br><br>';
    $output .= '<label>1.5 Melyik utasitassal tudunk SQL adatbazisban tablat letrehozni?</label><br>';
    $output .= '<input type="radio" name="1.5" value="1">MAKE TABLE<br>';
    $output .= '<input type="radio" name="1.5" value="2">CREATE TABLE<br>';
    $output .= '<input type="radio" name="1.5" value="3">NEW TABLE<br>';
    $output .= '<input type="radio" name="1.5" value="4">DROP TABLE<br>';
    $output .= '<br><br>';
    $output .= '<label>1.6 Minek lehet alnevet (ALIAS) adni egy SQL lekerdezesben?</label><br>';
    $output .= '<input type="radio" name="1.6" value="1">Mezoknek<br>';
    $output .= '<input type="radio" name="1.6" value="2">Tablaknak<br>';
    $output .= '<input type="radio" name="1.6" value="3">Mezoknek es tablaknak<br>';
    $output .= '<input type="radio" name="1.6" value="4">Mezoknek es zaradekoknak<br>';
    $output .= '<br><br>';
    $output .= '<label>1.7 A mar csoportositott adatok szuresere melyik SQL zaradek hasznalhato?</label><br>';
    $output .= '<input type="radio" name="1.7" value="1">WHERE<br>';
    $output .= '<input type="radio" name="1.7" value="2">WERE<br>';
    $output .= '<input type="radio" name="1.7" value="3">HAVING<br>';
    $output .= '<input type="radio" name="1.7" value="4">LIMIT<br>';
    $output .= '<br><br>';
    $output .= '<label>1.8 Melyik SQL utasitassal tudjuk megjeleniteni az Orszagok tabla minden adatat?</label><br>';
    $output .= '<input type="radio" name="1.8" value="1">SELECT *.Orszagok<br>';
    $output .= '<input type="radio" name="1.8" value="2">SELECT Orszagok<br>';
    $output .= '<input type="radio" name="1.8" value="3">SELECT FROM Orszagok<br>';
    $output .= '<input type="radio" name="1.8" value="4">SELECT * FROM Orszagok<br>';
    $output .= '<br><br>';
    $output .= '<label>1.9 Melyik SQL zaradekot kell alkalmazni annak erdekeben, hogy a lekerdezes eredmenye fizetes szerint novekvo sorrendben jelenjen meg?</label><br>';
    $output .= '<input type="radio" name="1.9" value="1">ORDER BY fizetes UP<br>';
    $output .= '<input type="radio" name="1.9" value="2">ORDER BY fizetes DESC<br>';
    $output .= '<input type="radio" name="1.9" value="3">ORDER BY fizetes ASC<br>';
    $output .= '<input type="radio" name="1.9" value="4">ORDER BY fizetes DOWN<br>';
    $output .= '<br><br>';
    $output .= '<label>1.10 Melyik zaradekkal korlatozhatjuk a megjeleno adatsorok szamat a lekerdezesekben?</label><br>';
    $output .= '<input type="radio" name="1.10" value="1">LAST<br>';
    $output .= '<input type="radio" name="1.10" value="2">TAKE<br>';
    $output .= '<input type="radio" name="1.10" value="3">TOP/LIMIT<br>';
    $output .= '<input type="radio" name="1.10" value="4">NUMBER OF<br><br>';
    return $output;
}
function MasodikKerdesek() {
    $output = '';
    $output .= '<div class="row">';
    $output .= '<div class="half">';
    $output .= '<img src="kerdessorok/masodik/IMG_0001.jpg" width="100%" height="auto"><br><br>';
    $output .= '</div>';
    $output .= '<div class="half">';
    $output .= '<img src="kerdessorok/masodik/IMG_0002.jpg" width="100%" height="auto"><br><br>';
    $output .= '</div>';
    $output .= '</div>';
    $output .= '<label>1.1</label><br>';
    $output .= '<input type="radio" name="1.1" value="A" >A<br>';
    $output .= '<input type="radio" name="1.1" value="B" >B<br>';
    $output .= '<input type="radio" name="1.1" value="C" >C<br>';
    $output .= '<input type="radio" name="1.1" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.2</label><br>';
    $output .= '<input type="radio" name="1.2" value="A" >A<br>';
    $output .= '<input type="radio" name="1.2" value="B" >B<br>';
    $output .= '<input type="radio" name="1.2" value="C" >C<br>';
    $output .= '<input type="radio" name="1.2" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.3</label><br>';
    $output .= '<input type="radio" name="1.3" value="A" >A<br>';
    $output .= '<input type="radio" name="1.3" value="B" >B<br>';
    $output .= '<input type="radio" name="1.3" value="C" >C<br>';
    $output .= '<input type="radio" name="1.3" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.4</label><br>';
    $output .= '<input type="radio" name="1.4" value="A" >A<br>';
    $output .= '<input type="radio" name="1.4" value="B" >B<br>';
    $output .= '<input type="radio" name="1.4" value="C" >C<br>';
    $output .= '<input type="radio" name="1.4" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.5</label><br>';
    $output .= '<input type="radio" name="1.5" value="A" >A<br>';
    $output .= '<input type="radio" name="1.5" value="B" >B<br>';
    $output .= '<input type="radio" name="1.5" value="C" >C<br>';
    $output .= '<input type="radio" name="1.5" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.6</label><br>';
    $output .= '<input type="radio" name="1.6" value="A" >A<br>';
    $output .= '<input type="radio" name="1.6" value="B" >B<br>';
    $output .= '<input type="radio" name="1.6" value="C" >C<br>';
    $output .= '<input type="radio" name="1.6" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.7</label><br>';
    $output .= '<input type="radio" name="1.7" value="A" >A<br>';
    $output .= '<input type="radio" name="1.7" value="B" >B<br>';
    $output .= '<input type="radio" name="1.7" value="C" >C<br>';
    $output .= '<input type="radio" name="1.7" value="D" >D<br>';
    $output .= '<input type="radio" name="1.7" value="E" >E<br>';
    $output .= '<input type="radio" name="1.7" value="F" >F<br>';
    $output .= '<input type="radio" name="1.7" value="G" >G<br>';
    $output .= '<input type="radio" name="1.7" value="H" >H<br>';
    $output .= '<br><br>';
    $output .= '<label>1.8</label><br>';
    $output .= '<input type="radio" name="1.8" value="A" >A<br>';
    $output .= '<input type="radio" name="1.8" value="B" >B<br>';
    $output .= '<input type="radio" name="1.8" value="C" >C<br>';
    $output .= '<input type="radio" name="1.8" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.9</label><br>';
    $output .= '<input type="radio" name="1.9" value="A" >A<br>';
    $output .= '<input type="radio" name="1.9" value="B" >B<br>';
    $output .= '<input type="radio" name="1.9" value="C" >C<br>';
    $output .= '<input type="radio" name="1.9" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.10</label><br>';
    $output .= '<input type="radio" name="1.10" value="A" >A<br>';
    $output .= '<input type="radio" name="1.10" value="B" >B<br>';
    $output .= '<input type="radio" name="1.10" value="C" >C<br>';
    $output .= '<input type="radio" name="1.10" value="D" >D<br>';
    return $output;
}
function HarmadikKerdesek() {
    $output = '';
    $output .= '<div class="row">';
    $output .= '<div class="half">';
    $output .= '<img src="kerdessorok/harmadik/IMG_0001.jpg" width="100%" height="auto"><br><br>';
    $output .= '</div>';
    $output .= '<div class="half">';
    $output .= '<img src="kerdessorok/harmadik/IMG_0002.jpg" width="100%" height="auto"><br><br>';
    $output .= '</div>';
    $output .= '</div>';
    $output .= '<label>1.1</label><br>';
    $output .= '<input type="radio" name="1.1" value="A" >A<br>';
    $output .= '<input type="radio" name="1.1" value="B" >B<br>';
    $output .= '<input type="radio" name="1.1" value="C" >C<br>';
    $output .= '<input type="radio" name="1.1" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.2</label><br>';
    $output .= '<input type="radio" name="1.2" value="A" >A<br>';
    $output .= '<input type="radio" name="1.2" value="B" >B<br>';
    $output .= '<input type="radio" name="1.2" value="C" >C<br>';
    $output .= '<input type="radio" name="1.2" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.3</label><br>';
    $output .= '<input type="radio" name="1.3" value="A" >A<br>';
    $output .= '<input type="radio" name="1.3" value="B" >B<br>';
    $output .= '<input type="radio" name="1.3" value="C" >C<br>';
    $output .= '<input type="radio" name="1.3" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.4</label><br>';
    $output .= '<input type="radio" name="1.4" value="A" >A<br>';
    $output .= '<input type="radio" name="1.4" value="B" >B<br>';
    $output .= '<input type="radio" name="1.4" value="C" >C<br>';
    $output .= '<input type="radio" name="1.4" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.5</label><br>';
    $output .= '<input type="radio" name="1.5" value="A" >A<br>';
    $output .= '<input type="radio" name="1.5" value="B" >B<br>';
    $output .= '<input type="radio" name="1.5" value="C" >C<br>';
    $output .= '<input type="radio" name="1.5" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.6</label><br>';
    $output .= '<input type="radio" name="1.6" value="A" >A<br>';
    $output .= '<input type="radio" name="1.6" value="B" >B<br>';
    $output .= '<input type="radio" name="1.6" value="C" >C<br>';
    $output .= '<input type="radio" name="1.6" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.7</label><br>';
    $output .= '<input type="radio" name="1.7" value="A" >A<br>';
    $output .= '<input type="radio" name="1.7" value="B" >B<br>';
    $output .= '<input type="radio" name="1.7" value="C" >C<br>';
    $output .= '<input type="radio" name="1.7" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.8</label><br>';
    $output .= '<input type="radio" name="1.8" value="A" >A<br>';
    $output .= '<input type="radio" name="1.8" value="B" >B<br>';
    $output .= '<input type="radio" name="1.8" value="C" >C<br>';
    $output .= '<input type="radio" name="1.8" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.9</label><br>';
    $output .= '<input type="radio" name="1.9" value="A" >A<br>';
    $output .= '<input type="radio" name="1.9" value="B" >B<br>';
    $output .= '<input type="radio" name="1.9" value="C" >C<br>';
    $output .= '<input type="radio" name="1.9" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    $output .= '<br><br>';
    $output .= '<label>1.10</label><br>';
    $output .= '<input type="radio" name="1.10" value="A" >A<br>';
    $output .= '<input type="radio" name="1.10" value="B" >B<br>';
    $output .= '<input type="radio" name="1.10" value="C" >C<br>';
    $output .= '<input type="radio" name="1.10" value="D" >D<br>';
    $output .= '<input type="radio" name="1.1" value="E" >E<br>';
    return $output;
}
function NegyedikKerdesek() {
    $output = '';
    $output .= '<div class="row">';
    $output .= '<div class="half">';
    $output .= '<img src="kerdessorok/negyedik/feladat-1.jpg" width="100%" height="auto"><br><br>';
    $output .= '<img src="kerdessorok/negyedik/feladat-2.jpg" width="100%" height="auto"><br><br>';
    $output .= '</div>';
    $output .= '<div class="half">';
    $output .= '<img src="kerdessorok/negyedik/feladat-3.jpg" width="100%" height="auto"><br><br>';
    $output .= '</div>';
    $output .= '</div>';
    $output .= '<label>1.1</label><br>';
    $output .= '<input type="radio" name="1.1" value="A" >A<br>';
    $output .= '<input type="radio" name="1.1" value="B" >B<br>';
    $output .= '<input type="radio" name="1.1" value="C" >C<br>';
    $output .= '<input type="radio" name="1.1" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.2</label><br>';
    $output .= '<input type="radio" name="1.2" value="A" >A<br>';
    $output .= '<input type="radio" name="1.2" value="B" >B<br>';
    $output .= '<input type="radio" name="1.2" value="C" >C<br>';
    $output .= '<input type="radio" name="1.2" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.3</label><br>';
    $output .= '<input type="radio" name="1.3" value="A" >A<br>';
    $output .= '<input type="radio" name="1.3" value="B" >B<br>';
    $output .= '<input type="radio" name="1.3" value="C" >C<br>';
    $output .= '<input type="radio" name="1.3" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.4</label><br>';
    $output .= '<input type="radio" name="1.4" value="A" >A<br>';
    $output .= '<input type="radio" name="1.4" value="B" >B<br>';
    $output .= '<input type="radio" name="1.4" value="C" >C<br>';
    $output .= '<input type="radio" name="1.4" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.5</label><br>';
    $output .= '<input type="radio" name="1.5" value="A" >A<br>';
    $output .= '<input type="radio" name="1.5" value="B" >B<br>';
    $output .= '<input type="radio" name="1.5" value="C" >C<br>';
    $output .= '<input type="radio" name="1.5" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.6</label><br>';
    $output .= '<input type="radio" name="1.6" value="A" >A<br>';
    $output .= '<input type="radio" name="1.6" value="B" >B<br>';
    $output .= '<input type="radio" name="1.6" value="C" >C<br>';
    $output .= '<input type="radio" name="1.6" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.7</label><br>';
    $output .= '<input type="radio" name="1.7" value="A" >A<br>';
    $output .= '<input type="radio" name="1.7" value="B" >B<br>';
    $output .= '<input type="radio" name="1.7" value="C" >C<br>';
    $output .= '<input type="radio" name="1.7" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.8</label><br>';
    $output .= '<input type="radio" name="1.8" value="A" >A<br>';
    $output .= '<input type="radio" name="1.8" value="B" >B<br>';
    $output .= '<input type="radio" name="1.8" value="C" >C<br>';
    $output .= '<input type="radio" name="1.8" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.9</label><br>';
    $output .= '<input type="radio" name="1.9" value="A" >A<br>';
    $output .= '<input type="radio" name="1.9" value="B" >B<br>';
    $output .= '<input type="radio" name="1.9" value="C" >C<br>';
    $output .= '<input type="radio" name="1.9" value="D" >D<br>';
    $output .= '<br><br>';
    $output .= '<label>1.10</label><br>';
    $output .= '<input type="radio" name="1.10" value="A" >A<br>';
    $output .= '<input type="radio" name="1.10" value="B" >B<br>';
    $output .= '<input type="radio" name="1.10" value="C" >C<br>';
    $output .= '<input type="radio" name="1.10" value="D" >D<br>';
    return $output;
}

